# docker-compose.yml
services:
  crosswatch:
    image: ghcr.io/cenodude/crosswatch:latest
    container_name: crosswatch
    ports:
      - "8787:8787"          # host:container
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - /path/to/data/data/com.termux/files/home/projects/CrossWatch:/data/data/com.termux/files/home/projects/CrossWatch
    restart: unless-stopped
